name: fast_cached_network_image
description: A flutter package to cache network image fastly without any native dependencies.You can add beautiful loaders, percentage indicators and error builder.
version: 1.2.1
homepage: https://github.com/CHRISTOPANANJICKAL/fast_cached_network_image
repository: https://github.com/CHRISTOPANANJICKAL/fast_cached_network_image
issue_tracker: https://github.com/CHRISTOPANANJICKAL/fast_cached_network_image/issues

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=3.16.4"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  hive_flutter: ^2.0.0-dev
  hive: ^3.0.0-dev
  uuid: ^4.2.2

